### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by lukasvy** [gangstead/atom-incremental-search#42] opened 2015-09-11 09:34 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [incremental-search](https://github.com/gangstead/atom-incremental-search) package, v5.0.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /C:/Users/lukas/.atom/packages/incremental-search/lib/search-model.coffee:230

TypeError: undefined is not a function
  at SearchModel.module.exports.SearchModel.findMarkerForward (C:\Users\lukas\.atom\packages\incremental-search\lib\search-model.coffee:226:77)
  at SearchModel.module.exports.SearchModel.moveToClosestResult (C:\Users\lukas\.atom\packages\incremental-search\lib\search-model.coffee:211:52)
  at SearchModel.module.exports.SearchModel.updateMarkers (C:\Users\lukas\.atom\packages\incremental-search\lib\search-model.coffee:200:6)
  at SearchModel.module.exports.SearchModel.update (C:\Users\lukas\.atom\packages\incremental-search\lib\search-model.coffee:273:8)
  at InputView.module.exports.InputView.updateSearchText (C:\Users\lukas\.atom\packages\incremental-search\lib\input-view.coffee:85:18)
  at C:\Users\lukas\.atom\packages\incremental-search\lib\input-view.coffee:30:50
  at Emitter.module.exports.Emitter.emit (C:\Users\lukas\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at C:\Users\lukas\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1263:25

```

### Commands

```
     -0:31.7.0 core:close (atom-text-editor.editor.is-focused)
 21x -0:30.1.0 incremental-search:forward (atom-text-editor.editor.is-focused)
     -0:23 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:23 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.8.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:21.8.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.7.0 command-palette:toggle (atom-text-editor.editor.mini.is-focused)
     -0:20.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:20.4.0 window:run-package-specs (atom-text-editor.editor.mini)
     -0:08.3.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:07.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.7.0 editor:toggle-soft-wrap (atom-text-editor.editor)
     -0:06.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:05.7.0 incremental-search:forward (atom-text-editor.editor.is-focused)
     -0:04.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "twilight-textmate-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
atom-alignment, v0.12.1
atom-ternjs, v0.7.2
atomatigit, v1.5.4
change-case, v0.6.0
color-picker, v2.0.11
incremental-search, v5.0.1
language-diff, v0.3.1
language-mason, v2.0.4
twilight-textmate-syntax, v0.1.19

# Dev
No dev packages
```

**Comment by gangstead** [comment] 2016-02-19 20:12
dupe of #35 fixed in `v5.0.2`

**Closed by gangstead** 2016-02-19 20:12 UTC
